apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice2
  labels:
    app: microservice2
    protected: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice2
  template:
    metadata:
      labels:
        app: microservice2
        protected: "true"
    spec:
      serviceAccountName: admin-sa
      containers:
      - name: microservice2
        image: justmorpheu5/microservice2:latest
        ports:
        - containerPort: 5001
        env:
        - name: SECRET_KEY
          value: secret
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
      nodeName: Worker-2

