apiVersion: v1
kind: Service
metadata:
  name: microservice2
  labels:
    app: microservice2
    protected: "true"
spec:
  type: NodePort
  selector:
    app: microservice2
  ports:
  - name: http-5001
    protocol: TCP
    port: 5001
    targetPort: 5001
    nodePort: 30002
