apiVersion: v1
kind: Pod
metadata:
  name: hostipc-vuln-pod
  namespace: legacy
  labels:
    app: myapp-legacy
    protected: "true"
spec:
  hostIPC: true
  hostNetwork: true
  hostPID: true
  containers:
  - name: vuln-container
    image: ubuntu
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  nodeName: Worker-3
