apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: list-secrets-legacy
  namespace: legacy
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list"]
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods", "nodes", "svc"]
  verbs: ["exec","get", "list", "watch","logs"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]
  resourceNames: [""]
