apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: list-secrets-legacy
  namespace: legacy
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["pods","deployment","nodes"]
  verbs: ["exec","logs","get","list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]
  resourceNames: [""]
